[tool.isort]
profile="black"
line_length=119

[tool.black]
line-length = 119

[dependency-groups]
dev = [
    "beartype>=0.22.2",
    "braceexpand>=0.1.7",
    "colorlog>=6.10.1",
    "decord2>=3.0.0",
    "einops>=0.8.1",
    "fire>=0.7.1",
    "ftfy>=6.3.1",
    "gcsfs>=2025.12.0",
    "h5py>=3.14.0",
    "iopath>=0.1.10",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.0.2",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.3",
    "peft>=0.17.1",
    "psutil>=7.2.1",
    "python-box>=7.3.2",
    "pyyaml>=6.0.3",
    "scikit-image>=0.24.0",
    "submitit>=1.5.4",
    "tensorboard>=2.20.0",
    "tensorflow-datasets>=4.9.9",
    "timm>=1.0.22",
    "torch>=2",
    "torchvision>=0.23.0",
    "transformers>=4.57.3",
    "wandb>=0.23.1",
    "webdataset>=0.2.100",
]
